Update NixOS stable.
The `intel` -> `modesetting` change is due to new eval error:

    error: xf86videointel has been removed as the package is unmaintained and the driver is no longer functional.
    Please remove "intel" from `services.xserver.videoDrivers` and switch to the "modesetting" driver.

Looks like I should have been using `modesetting` for a while now.
Hopefully also explains why my `intel` specialisation hasn't booted
successfully since the upgrade to NixOS 24.11 (or so).