Upgrade NixOS 24.11 -> 25.05.
Addressed the following incompatibilites:

    The option definition `services.locate.localuser' in `/etc/nixos/configuration.nix' no longer has any effect; please remove it.

    error: 'xournal' has been removed due to lack of activity upstream and depending on gnome2. Consider using 'xournalpp' instead.

    evaluation warning: The option `hardware.pulseaudio' defined in `/etc/nixos/configuration.nix' has been renamed to `services.pulseaudio'.

And:

* luminanceHDR does not currently build; I made a nixpkgs PR to fix it, but don't need this software any more.